name: spring-javaconfig-example

on:
  push:
    paths:
      - "spring-javaconfig-example/**"
    branches: [master]
  pull_request:
    paths:
      - "spring-javaconfig-example/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "spring-javaconfig-example"
    strategy:
      matrix:
        distribution: [ 'temurin' ]
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw clean verify
